# Generated by Django 4.1.1 on 2023-04-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComunidadAutonoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeriaMercadillo",
            fields=[
                ("id_fm", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_fm", models.CharField(max_length=100)),
                ("días_fm", models.CharField(max_length=100)),
                ("tipo_fm", models.CharField(max_length=100, null=True)),
                ("ubicación_fm", models.CharField(max_length=200)),
                ("horario_fm", models.CharField(max_length=100, null=True)),
                ("num_puestos_fm", models.IntegerField(null=True)),
                ("descripción_fm", models.TextField(null=True)),
                ("latitude_fm", models.FloatField(blank=True, null=True)),
                ("longitude_fm", models.FloatField(blank=True, null=True)),
                (
                    "ccaa_fm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.comunidadautonoma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provincia", models.CharField(max_length=100, unique=True)),
                (
                    "comunidad_autonoma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provincias",
                        to="Marketplace.comunidadautonoma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoVenta",
            fields=[
                ("id_tipo_venta", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_venta", models.CharField(max_length=100)),
                ("descripción_venta", models.TextField()),
                ("ventajas_venta", models.TextField()),
                ("desventajas_venta", models.TextField()),
                ("normativa_venta", models.TextField()),
                ("inscripción_venta", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Productor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("id_regepa", models.CharField(max_length=10, unique=True)),
                ("dni_prod", models.CharField(max_length=10)),
                ("nombre_prod", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cp_prod", models.CharField(blank=True, max_length=10, null=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "teléfono_prod",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "ccaa_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.comunidadautonoma",
                    ),
                ),
                (
                    "ferias_mercadillos",
                    models.ManyToManyField(
                        related_name="productores", to="Marketplace.feriamercadillo"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "productos_prod",
                    models.ManyToManyField(
                        blank=True,
                        related_name="productores",
                        to="Marketplace.producto",
                    ),
                ),
                (
                    "provincia_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.provincia",
                    ),
                ),
                (
                    "tipos_venta",
                    models.ManyToManyField(
                        related_name="productores", to="Marketplace.tipoventa"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductorURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "productor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feriamercadillo",
            name="provincia_fm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Marketplace.provincia"
            ),
        ),
        migrations.CreateModel(
            name="EncuestaRegistroVentaDirecta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registro", models.CharField(max_length=1)),
                ("informacion", models.CharField(max_length=1)),
                ("facilidad", models.CharField(max_length=1)),
                ("recomendacion", models.CharField(max_length=1)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "productor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncuestaMercadillos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uso", models.CharField(max_length=1)),
                ("utilidad", models.CharField(max_length=1)),
                ("accesibilidad", models.CharField(max_length=1)),
                ("participacion", models.CharField(max_length=1)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "productor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncuestaComunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frecuencia_uso", models.CharField(max_length=1)),
                ("utilidad", models.CharField(max_length=1)),
                ("eficacia", models.CharField(max_length=1)),
                ("negocios", models.CharField(max_length=1)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "productor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DireccionesProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=200)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("codigo_postal", models.CharField(max_length=10)),
                (
                    "productor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.provincia",
                    ),
                ),
                (
                    "tipo_venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.tipoventa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cooperativa",
            fields=[
                ("id_coop", models.AutoField(primary_key=True, serialize=False)),
                ("num_inscripcion", models.CharField(max_length=200)),
                ("denominación_social", models.CharField(max_length=200)),
                ("localidad_coop", models.CharField(max_length=200)),
                ("cp_coop", models.CharField(max_length=10)),
                ("grado_coop", models.CharField(max_length=200)),
                ("fecha_inscripcion_coop", models.DateField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "ccaa_coop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.comunidadautonoma",
                    ),
                ),
                (
                    "provincia_coop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Marketplace.provincia",
                    ),
                ),
            ],
        ),
    ]
