# Generated by Django 4.1.1 on 2023-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feriamercadillo",
            name="ubicación_fm",
            field=models.CharField(max_length=300),
        ),
    ]
